### ISSUE TITLE
Make LessCompiler thread safe

### ISSUE THREAD

**Issue by candrews** [marceloverdijk/lesscss-java#11]
Right now, the LessCompiler instance cannot be reused between threads. It also doesn't call Context.exit(), so it doesn't detach from the thread it's on. These 2 problems cause terrible performance and wasted memory when LessCompiler is used on application servers.

I found a similar project that does handle multithreading well: it only initializes rhino once, loads the scripts, and reuses the scope so that the scripts don't need to be re-evaluated for every thread. This drastically improves performance and reduces memory use. We may want to use it as a reference in improving this project: https://github.com/ultraq/lesscss-filter/blob/master/Java/nz/net/ultraq/web/lesscss/LessCSSProcessor.java

**Comment by candrews** [comment]
Done ff044a4a83c528f9a5abdae99c350aa03bcdcf83

**Comment by cplim** [comment]
Hi,

I understand that this was done awhile ago, but is making the LessCompiler intrinsically thread-safe the best approach?  What is the issue with creating a LessCompiler instance per thread?  The reason I ask this is if I am not using the compiler in a multi-threaded environment, I pay the penalty of synchronized calls on the compile() method.

regards,
CP

**Comment by candrews** [comment]
If you're in a single threaded environment, then synchronization will always be incredibly cheap (essentially free) as the semaphores will always be instantly acquired.
The problem with making a LessCompiler instance per thread is that each instance will have its own Rhino and everything else, which takes a long time to create and takes a lot of memory.  Having the LessCompiler be thread safe and reusing the same instance globally saves an impressive amount of time and memory.

**Comment by cplim** [comment]
Ok, thanks for the update.  I also did a few performance runs and the numbers seem to backup what you've said.  Thanks.
