### ISSUE TITLE
Bad version of less.css embedded in lesscss-java 1.3.1 ?

### ISSUE THREAD

**Issue by ghusta** [marceloverdijk/lesscss-java#12]
The version of less.css embedded in lesscss-java 1.3.1 is 1.3.0.
See : https://github.com/marceloverdijk/lesscss-java/blob/lesscss-1.3.1/src/main/resources/META-INF/less.js

Shouldn't it be [less.js 1.3.1](https://github.com/cloudhead/less.js/blob/master/dist/less-1.3.1.js) ?

**Comment by marceloverdijk** [comment]
Yes @candrews released 1.3.1 of the less compiler adding new features. But this was based on less 1.3.0.

I don't have time to update to less 1.3.1 unfortunately.

**Comment by ghusta** [comment]
OK thanks.

**Comment by ghusta** [comment]
Nevertheless, I think it would have sense if lesscss-java versions were aligned to those of lesscss.js.  
As it was the case with the version 1.3.0.  
However it's true that one can use any version of lesscss.js by using the lesscss-maven-plugin CompileMojo's _lessJs_ parameter.

**Comment by candrews** [comment]
less.js doesn't release very often... so it's hard to sync up the releases of this plugin with less.js. For example, should releases of plugin should wait for new versions of less.js to be released? Even if there are new features and bug fixes?

**Comment by candrews** [comment]
I bumped the bundled version of less.js to 1.3.1: 4818c769ef670daea90c328656b01b9a951d7810

Since it seems that a few people are already using this version of less.js with this plugin, and all the tests pass, this seems pretty safe.
