### ISSUE TITLE
Versions consistent with less.js

### ISSUE THREAD

**Issue by verglor** [marceloverdijk/lesscss-java#20]
I suggest to change version pattern to version of included less.js.
For example current version 1.3.1 contains less.js 1.3.0 and 1.3.2-SNAPSHOT contains less.js 1.3.1 which is very confusing.
Maybe another minor subversion colud be added to distinguish between different versions with the same less.js (e.g. 1.3.1.x for less.js 1.3.1)

**Comment by cpopov** [comment]
Agreed
