### ISSUE TITLE
Mixing String and File sources

### ISSUE THREAD

**Issue by msgilligan** [marceloverdijk/lesscss-java#3]
I want to be able to build something like this:
http://twitter.github.com/bootstrap/download.html#variables

From the API Docs I don't see a way to do it.  Do you do it with CustomJS?

**Comment by marceloverdijk** [comment]
I don't understand what you are trying to accomplish.
That page you mention allows you to customize bootstrap vars and then download the generated css.
What that page is doing is actually compiling the bootstrap LESS on the server with the given values and allowing you to download the css.

What should lesscss-java offer in this you think?
I don't see the relation.

**Comment by msgilligan** [comment]
I don't want to have to generate a java.io.File object from the Web Form.  I want to take the form inputs, feed them in to a string template, prefix that string to a list of files and generate a single CSS file on the fly and stream it out.

I don't see a way to create a LessSource object from a string.  Or reference File or LessSource objects from a string.

**Comment by marceloverdijk** [comment]
The only thing the LessSource is doing is actually resolving imports. Remember that if there would be String argument constructor for LessSource, how should it be able to resolve (relative) imports then?

Don't you just want to do:

```
LessCompiler lessCompiler = new LessCompiler();
String css = lessCompiler.compile("your less code goes here");
```

**Comment by msgilligan** [comment]
The String constructor would also take a File parameter for the base directory for imports, of course.  :)

I don't want to have to read in all the files off disk and create my own string.  But I suppose it wouldn't be that hard.

**Comment by marceloverdijk** [comment]
Why not use something like:

```
String vars = ".."; // <-- the vars from your form
LessSource lessSource = new LessSource(..);
String less = vars + "\n" + lessSource.getNormalizedContent();
LessCompiler lessCompiler = new LessCompiler();
String css = lessCompiler.compile(less);
```

**Comment by msgilligan** [comment]
Yeah, that should do the trick.  Thanks!

**Comment by marceloverdijk** [comment]
Maybe not the most beautiful solution but it indeed should do the trick.
Don't feel comfortable with adding LessSource(File basePath, String content) at the moment as it is imo a corner case.
If more people will request I will reconsider. Hope you understand.

**Comment by msgilligan** [comment]
I understand.  I just want to hack together a quick Servlet or SpringMVC Controller for a demo.  Once I get something working, I'll post it (assuming I don't get sidetracked by paying projects)
