### ISSUE TITLE
Update for less 1.4

### ISSUE THREAD

**Issue by ersubodhgupta** [marceloverdijk/lesscss-java#34]
Actually my project is currently using less 1.4 @runtime and want to move the templates to compile @build time. I was looking at this plugin for this purpose only to realise that it works on 1.3.3 less.

So is there any plan to move it 1.4?

**Comment by cpopov** [comment]
The new release will support the latest 1.4.1

**Comment by expjson** [comment]
@cpopov When can we expect the new version?

**Comment by bbrouwer** [comment]
I just built the latest and it isn't working. It appears the pattern matcher group indexes changed when changing LessSource.IMPORT_PATTERN. I simply added 1 to each group index in LessSource.resolveImports to fix it.

**Comment by emecell** [comment]
Yeah, I was running into the same issue earlier. 

I was also wondering what the plan was to support the new data URI function in 1.4?

**Comment by chubbard** [comment]
What's the deal here?  Is this getting fixed anytime soon?  Less is already on 1.5.0.

**Comment by cpopov** [comment]
it looks like all contributors are very busy (inclduing me). Do you want to become a commiter? Talk to Marcel he will give you rights

**Comment by chubbard** [comment]
Yes I might be into do that.  The code is not in a good state.  If you can explain where it stands and what is missing.  The unit tests aren't working, but there are some compatibility tests.  Do those include tests from less project?  Have they been updated to 1.4?
