### ISSUE TITLE
Bootstrap 3.1 vs. Less 1.6.x

### ISSUE THREAD

**Issue by BurnedToast** [marceloverdijk/lesscss-java#43]
The latest Bootstrap-Update 3.1 announced that they switched from Recess to grunt-contrib-less as a compiler. So they now can use Less 1.6.x.

Will this Project be able to support Less 1.6.x? 
If yes - when could this be available?

Thanks in advance

**Comment by lbehnke** [comment]
+1 for update to less 1.6.x

**Comment by codler** [comment]
+1

**Comment by sandroboehme** [comment]
+1

**Comment by jamesxabregas** [comment]
+1

**Comment by mikhail-tokarev** [comment]
+1

**Comment by paulcitarella** [comment]
+1

**Comment by diffcunha** [comment]
+1

**Comment by tcrossland** [comment]
This seems to be solved by pull request #42.

**Comment by BurnedToast** [comment]
I did a quick test - it seems to work with pull request #42!
I will try it more extensive the next days!

Thank you very much

**Comment by sandroboehme** [comment]
Fixed the Bootstrap tests for the source of the pull request #42

**Comment by sandroboehme** [comment]
Fixed the MultithreadedIT.java test there as well.

**Comment by sandroboehme** [comment]
## There are only three test classes that contain failing tests using the pull request #42:

## LessSourceTest

It contains some functionality that has to be mocked differently as the underlying framework behaves different now. I will work on that in the next days.

## ImportIT

Contains 4 tests. Only the testHttpImport test is failing. Result:
<[FileError: 'font-awesome.less' wasn't found in /lesscss-java/target/test-classes/import/less/http_import.less on line 2, column 1:
1 //@import "http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css";
2 @import "https://raw2.github.com/FortAwesome/Font-Awesome/master/less/font-awesome.less";
3 ]


Does anybody have an idea to get the https import working?

## CompatibilityIT

Contains 27 test. Only the testVariables test is failing. Result:
<[ParseError: Unrecognised input in /lesscss-java/target/test-classes/compatibility/less/variables.less on line 52, column 13:
51 
52 a:nth-child(@a) {
53     border: 1px;]


This error appears even if @a is defined in line 1 like this:
@a: 2;
I didn't try to compile that in the browser yet.

**Comment by sandroboehme** [comment]
Closing as it has been released.
