### ISSUE TITLE
The JAR proposed on Maven Central contains SLF4J classes

### ISSUE THREAD

**Issue by gdelhumeau** [marceloverdijk/lesscss-java#51]
Hi.

I have recently found out that the JAR proposed there:
http://search.maven.org/#artifactdetails|org.lesscss|lesscss|1.7.0.1.0|jar
contains SLF4J classes.

It is a problem because these classes can already be there in the user classpath. We usually use dependencies exclusions to fix that kind of things:
http://www.slf4j.org/codes.html#multiple_bindings

But we just cannot if the classes are packaged in the JAR.

Thanks,
Guillaume

**Comment by sandroboehme** [comment]
Hi Guillaume,
#52 should fix that. Can you please build the project locally and confirm?

Best,

Sandro

**Comment by gdelhumeau** [comment]
Hi Sandro, and thanks for your answer :)

It looks good.

Thanks,
Guillaume

**Comment by sandroboehme** [comment]
Thanks for checking. The new version containing Davids fix has been released now.

**Comment by gdelhumeau** [comment]
Thanks! I have updated my project and everything is working fine :)

Guillaume

**Comment by sandroboehme** [comment]
Thanks for the info. I'm happy to read that.
