### ISSUE TITLE
rhino1_7R4 support - 1 line change required

### ISSUE THREAD

**Issue by pwujek** [marceloverdijk/lesscss-java#7]
rhino1_7R4 is the current version of Rhino.

change line 251 in LessCompiler.java from:
String message = (String)ScriptableObject.getProperty(value, "message");
to:
String message = ScriptableObject.getProperty(value, "message").toString();

**Comment by pwujek** [comment]
Oops! 

Unfortunately that is not enough to get this version of Rhino to work.

On a large .less file (>2,600 lines) a StackOverflowException is thrown in Rhino1_7R4 but not using Rhino1_7R3.

**Comment by candrews** [comment]
@pwujek I updated to Rhino 1.7R4, and all tests pass. I cannot reproduce your problem. Can you attach a file which causes a problem, and I'll see if I can figure out what's going wrong?

**Comment by candrews** [comment]
Bumped to Rhino 1.7R4 2f9cba28721ffcf0d6e36e46c43c80d7486004ad
